# Generated by Django 5.1.6 on 2025-02-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=255)),
                ('latency', models.IntegerField()),
                ('packet_loss', models.FloatField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
